### ISSUE TITLE
Maze list is empty on Chromium

### ISSUE THREAD

**Issue by Besfr** [ApolloNet/amazing-mazes#1]
See screenshot, no error in the console.
![maze_load](https://user-images.githubusercontent.com/152320/43044814-bfeb7bc2-8dad-11e8-8b36-9f33a62a7d3e.jpeg)

Use a Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.11 (64-bit)

**Comment by 413xr0n54u7** [comment]
Thank you for the issue.
No problem with my chromium, version 67.0.3396.99.
Issue will be solved with an error message for the old browsers that don't support modern CSS & JS.
It's already planned in the TODO.md, so i close here.
